---
title: "JSC370 Final Project"
author: "Hongshuo Zhou"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r load-data, echo=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

library(ggplot2)
library(leaflet)
library(readxl)
#install.packages("DT")
library(patchwork)
library(gridExtra)


# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")

```


```{r, include=FALSE, echo=FALSE}
academic <- read_excel("academic.xlsx")
academic <- academic |>
  select(-c("Progress in Four Year Graduation Rate", 
            "Five Year Graduation Rate", 
            "Four Year Graduation Rate", 
            "Progress in Five Year Graduation Rate", 
            "Progress in Primary Class Size with 20 Students or less", 
            "Primary Class Size with 20 Students or less", 
            "Progress in Credit Accumulation by the end of Grade 10", 
            "Progress in Credit Accumulation by the end of Grade 11",
            "Credit Accumulation by the end of Grade 10", 
            "Credit Accumulation by the end of Grade 11", 
            "Progress in Grade 6 EQAO Reading Results", 
            "Progress in Grade 10 OSSLT Results"))
```

```{r, include=FALSE, echo=FALSE}
school_info <- read_excel("school_info.xlsx")
school_info <- school_info |>
  select("Region",
         "Board Number",
         "Board Name",
         "Board Language",
         "School Number",
         "School Name",
         "School Level",
         "School Language",
         "School Type",
         "City")
```

```{r, include=FALSE, echo=FALSE}
data4 <- read_excel("gender_2011-12_en.xlsx")
data4 <- data4 %>%
  mutate('Start Year' = 2011)

data5 <- read_excel("gender_2012-2013_en_0.xlsx")
data5 <- data5 %>%
  mutate('Start Year' = 2012)

data6 <- read_excel("gender_2013-2014_en.xlsx")
data6 <- data6 %>%
  mutate('Start Year' = 2013)

data7 <- read_excel("gender_2014.xlsx")
data7 <- data7 %>%
  mutate('Start Year' = 2014)

data8 <- read_excel("gender_2015.xlsx")
data8 <- data8 %>%
  mutate('Start Year' = 2015)

data9 <- read_excel("gender_2016.xlsx")
data9 <- data9 %>%
  mutate('Start Year' = 2016)

data10 <- read_excel("enrolment_by_gender_1718_en.xlsx")
data10 <- data10 %>%
  mutate('Start Year' = 2017)

data11 <- read_excel("enrolment_by_gender_1819_en.xlsx")
data11 <- data11 %>%
  mutate('Start Year' = 2018)

data12 <- read_excel("gender_1920_en.xlsx")
data12 <- data12 %>%
  mutate('Start Year' = 2019)

data11 <- data11 |>
  rename(
    `Elementary Male Enrolment` = `Elementary Male`,
    `Elementary Female Enrolment` = `Elementary Female`,
    `Secondary Male Enrolment` = `Secondary Male`,
    `Secondary Female Enrolment` = `Secondary Female`,
    `Total Male Enrolment` = `Total Male`,
    `Total Female Enrolment` = `Total Female`
  )

data12 <- data12 |>
  rename(
    `Elementary Male Enrolment` = `Elementary Male`,
    `Elementary Female Enrolment` = `Elementary Female`,
    `Secondary Male Enrolment` = `Secondary Male`,
    `Secondary Female Enrolment` = `Secondary Female`,
    `Total Male Enrolment` = `Total Male`,
    `Total Female Enrolment` = `Total Female`
  )

student <- rbind(data4, data5, data6, data7, data8, data9, data10, data11, data12)
```

```{r, include=FALSE, echo=FALSE}
data15 <- read_excel("edu_gender_1516_en.xlsx")
data15 <- data15 %>%
  mutate('Start Year' = 2015)

data16 <- read_excel("edu_gender_1617_en_0.xlsx")
data16 <- data16 %>%
  mutate('Start Year' = 2016)

data17 <- read_excel("edu_gender_1718.xlsx")
data17 <- data17 %>%
  mutate('Start Year' = 2017)

data18 <- read_excel("edu_gender_1819.xlsx")
data18 <- data18 %>%
  mutate('Start Year' = 2018)

data19 <- read_excel("edu_gender_1920.xlsx")
data19 <- data19 %>%
  mutate('Start Year' = 2019)

educator <- rbind(data15, data16, data17, data18, data19) |>
  select(-c("Academic Year"))


```

```{r, include=FALSE, echo=FALSE}
expulsion <- read_excel("expulsions_0708_2021.xlsx")
expulsion <- expulsion |>
  select("Board Number",
         "Board Name",
         "2007-2008 Expulsion Rate",
         "2008-2009 Expulsion Rate",
         "2009-2010 Expulsion Rate",
         "2010-2011 Expulsion Rate",
         "2011-2012 Expulsion Rate",
         "2012-2013 Expulsion Rate",
         "2013-2014 Expulsion Rate",
         "2014-2015 Expulsion Rate",
         "2015-2016 Expulsion Rate",
         "2016-2017 Expulsion Rate",
         "2017-2018 Expulsion Rate",
         "2018-2019 Expulsion Rate",
         "2019-2020 Expulsion Rate",
         "2020-2021 Expulsion Rate")

expulsion <- expulsion |>
  mutate("2007" = 2007,
         "2008" = 2008,
         "2009" = 2009,
         "2010" = 2010,
         "2011" = 2011,
         "2012" = 2012,
         "2013" = 2013,
         "2014" = 2014,
         "2015" = 2015,
         "2016" = 2016,
         "2017" = 2017,
         "2018" = 2018,
         "2019" = 2019,
         "2020" = 2020)

new_expulsion <- data.frame("Expulsion Rate" = c(
         expulsion$"2007-2008 Expulsion Rate",
         expulsion$"2008-2009 Expulsion Rate",
         expulsion$"2009-2010 Expulsion Rate",
         expulsion$"2010-2011 Expulsion Rate",
         expulsion$"2011-2012 Expulsion Rate",
         expulsion$"2012-2013 Expulsion Rate",
         expulsion$"2013-2014 Expulsion Rate",
         expulsion$"2014-2015 Expulsion Rate",
         expulsion$"2015-2016 Expulsion Rate",
         expulsion$"2016-2017 Expulsion Rate",
         expulsion$"2017-2018 Expulsion Rate",
         expulsion$"2018-2019 Expulsion Rate",
         expulsion$"2019-2020 Expulsion Rate",
         expulsion$"2020-2021 Expulsion Rate"),
         "Start Year" = c(
           expulsion$"2007",
         expulsion$"2008",
         expulsion$"2009",
         expulsion$"2010",
         expulsion$"2011",
         expulsion$"2012",
         expulsion$"2013",
         expulsion$"2014",
         expulsion$"2015",
         expulsion$"2016",
         expulsion$"2017",
         expulsion$"2018",
         expulsion$"2019",
         expulsion$"2020"
         ),
         "Board Name" = c(
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name"
         ),
         "Board Number" = c(
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number"
         ))
```

```{r, include=FALSE, echo=FALSE}
suspension <- read_excel("suspensions_0708-2021.xlsx")

suspension <- suspension |>
  select("Board Number",
         "Board Name",
         "2007-2008 Suspension Rate",
         "2008-2009 Suspension Rate",
         "2009-2010 Suspension Rate",
         "2010-2011 Suspension Rate",
         "2011-2012 Suspension Rate",
         "2012-2013 Suspension Rate",
         "2013-2014 Suspension Rate",
         "2014-2015 Suspension Rate",
         "2015-2016 Suspension Rate",
         "2016-2017 Suspension Rate",
         "2017-2018 Suspension Rate",
         "2018-2019 Suspension Rate",
         "2019-2020 Suspension Rate",
         "2020-2021 Suspension Rate")

suspension <- suspension |>
  mutate("2007" = 2007,
         "2008" = 2008,
         "2009" = 2009,
         "2010" = 2010,
         "2011" = 2011,
         "2012" = 2012,
         "2013" = 2013,
         "2014" = 2014,
         "2015" = 2015,
         "2016" = 2016,
         "2017" = 2017,
         "2018" = 2018,
         "2019" = 2019,
         "2020" = 2020)

new_suspension <- data.frame("Suspension Rate" = c(
         suspension$"2007-2008 Suspension Rate",
         suspension$"2008-2009 Suspension Rate",
         suspension$"2009-2010 Suspension Rate",
         suspension$"2010-2011 Suspension Rate",
         suspension$"2011-2012 Suspension Rate",
         suspension$"2012-2013 Suspension Rate",
         suspension$"2013-2014 Suspension Rate",
         suspension$"2014-2015 Suspension Rate",
         suspension$"2015-2016 Suspension Rate",
         suspension$"2016-2017 Suspension Rate",
         suspension$"2017-2018 Suspension Rate",
         suspension$"2018-2019 Suspension Rate",
         suspension$"2019-2020 Suspension Rate",
         suspension$"2020-2021 Suspension Rate"),
         "Start Year" = c(
           suspension$"2007",
         suspension$"2008",
         suspension$"2009",
         suspension$"2010",
         suspension$"2011",
         suspension$"2012",
         suspension$"2013",
         suspension$"2014",
         suspension$"2015",
         suspension$"2016",
         suspension$"2017",
         suspension$"2018",
         suspension$"2019",
         suspension$"2020"
         ),
         "Board Name" = c(
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name"
         ),
         "Board Number" = c(
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number"
         ))

# educator 
# student 
# academic c
# school_info c
# new expulsion c
# new suspension c
```


```{r, include = FALSE, echo=FALSE}

# merge all six tables
dat1 <- merge(
  # Data
  x = academic,
  y = educator,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Board Type.x` == `Board Type.y`,
         `Board Language.x` == `Board Language.y`) |>
  select(-c(`Board Name.y`, `Board Type.y`, `Board Language.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Board Type" = `Board Type.x`,
         "Board Language" = `Board Language.x`)
```

```{r, include = FALSE, echo=FALSE}
dat1 <- merge(
  # Data
  x = dat1,
  y = student,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Start Year.x` == `Start Year.y`) |>
  select(-c(`Board Name.y`, `Start Year.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Start Year" = `Start Year.x`)
```

```{r, include = FALSE, echo=FALSE}
dat1 <- merge(
  # Data
  x = dat1,
  y = school_info,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Board Language.x` == `Board Language.y`) |>
  select(-c(`Board Name.y`, `Board Language.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Board Language" = `Board Language.x`,
         "Board City" = `City.x`,
         "School City" = `City.y`,
         "Board Region" = `Region.x`,
         "School Region" = `Region.y`
         )

```

```{r, include = FALSE, echo=FALSE}
dat1 <- merge(
  # Data
  x = dat1,
  y = new_expulsion,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`))

```

```{r, include = FALSE, echo=FALSE}

dat1 <- merge(
  # Data
  x = dat1,
  y = new_suspension,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`)) |>
  rename("Expulsion Rate" = `Expulsion.Rate`,
         "Suspension Rate" = `Suspension.Rate`)

```

```{r, include=FALSE, echo=FALSE}
dat1 <- na.omit(dat1)

# create new variable student teacher ratio

dat1$`Elementary Male Enrolment` <- as.numeric(dat1$`Elementary Male Enrolment`)
dat1$`Elementary Female Enrolment` <- as.numeric(dat1$`Elementary Female Enrolment`)

dat1$`Elementary Male Educators` <- as.numeric(dat1$`Elementary Male Educators`)
dat1$`Elementary Female Educators` <- as.numeric(dat1$`Elementary Female Educators`)

dat1$`Secondary Male Enrolment` <- as.numeric(dat1$`Secondary Male Enrolment`)
dat1$`Secondary Female Enrolment` <- as.numeric(dat1$`Secondary Female Enrolment`)

dat1$`Secondary Male Educators` <- as.numeric(dat1$`Secondary Male Educators`)
dat1$`Secondary Female Educators` <- as.numeric(dat1$`Secondary Female Educators`)

sum(is.na(dat1))
dat1 <- na.omit(dat1)

dat1 <- dat1 |>
  mutate("Elementary Student Teacher Ratio" = (`Elementary Male Enrolment` + `Elementary Female Enrolment`) /
           (`Elementary Male Educators` + `Elementary Female Educators`),
         "Secondary Student Teacher Ratio" = (`Secondary Male Enrolment` + `Secondary Female Enrolment`) /
           (`Secondary Male Educators` + `Secondary Female Educators`)
           ) 

str(dat1)
```



```{r, echo=FALSE}
# datatable(
#   head(dat1, 5), 
#   options = list(
#     scrollX = TRUE, 
#     scrollY = FALSE,
#     paging = FALSE,
#     dom = 't'
#   ),
#   rownames = FALSE,
#   caption = "Table 1 - First 5 rows of the final merged dataset"
# ) |>
# formatStyle(
#   columns = 1:34,
#   border = "0.5px solid black"
# )

```



```{r, echo=FALSE, echo=FALSE}
data <- read.csv("document.csv")

data <- data |>
  select(-("ID")) |>
  rename("Variable Name" = Variable.Name,
         "Variable Description" = Occupational.title)

# datatable(
#   data, 
#   options = list(
#     scrollX = FALSE, 
#     scrollY = "300px",
#     paging = FALSE,
#     dom = 't'
#   ),
#   rownames = FALSE,
#   caption = "Table 2"
# ) %>%
# formatStyle(
#   columns = 1:2,
#   border = "1px solid black"
# )
```



```{r, echo = FALSE, echo=FALSE}
plt3 <- dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_bar(aes(x = `School Region`, fill = `School Region`)) +
  labs(title = "Figure 1 - A barplot of the number of schools in each region",
       y = "Count",
       x = "School Region") +
  coord_flip() +
  theme_bw()

plt3 <- ggplotly(plt3)
```


```{r, echo = FALSE, warning=FALSE, echo=FALSE}
dat1$`Start Year` <- as.factor(dat1$`Start Year`)

plt2 <- dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_histogram(aes(x = `Secondary Student Teacher Ratio`), fill = "orange", color = "black", bins=30) +
  labs(title = "Figure 2 - A histogram of the Secondary Student-Teacher Ratio",
       y = "Count",
       x = "Secondary Student Teacher Ratio") +
  theme_bw()
plt2 <- ggplotly(plt2)
```

```{r, echo=FALSE, warning=FALSE, echo=FALSE}
# plot2 <- dat1 |>
#   filter(`Start Year` == 2018) |>
#   ggplot() +
#   geom_histogram(aes(x = `Elementary Student Teacher Ratio`), fill = "orange", color = "black", bins=30) +
#   labs(title = "Figure 3 - A histogram of the Elementary Student-Teacher Ratio",
#        y = "Count",
#        x = "Elementary Student Teacher Ratio") +
#   theme_bw()
# 
# # grid.arrange(plot1, plot2, ncol=1)
# plt2 <- ggplotly(plt2)
```


```{r, echo=FALSE}

dat1$`Grade 10 OSSLT Results` <- as.numeric(dat1$`Grade 10 OSSLT Results`)

plot1 <- dat1 |>
  ggplot() +
  geom_boxplot(aes(x = `Grade 10 OSSLT Results`), fill="gray", color = "black") +
  labs(title = "Figure 4 - A boxplot for \nthe Grade 10 OSSLT Results",
       x = "Grade 10 OSSLT Results") +
  scale_fill_brewer(palette = "Paired") +
  theme_bw() +
  coord_flip()

# plt3 <- dat1 |>
#   ggplot() +
#   geom_boxplot(aes(x = `Grade 6 EQAO Reading Results`), fill="gray", color = "black") +
#   labs(title = "Figure 5 - A boxplot for \nGrade 6 EQAO Reading Results",
#        x = "Grade 6 EQAO Reading Results") +
#   scale_fill_brewer(palette = "Paired") +
#   theme_bw() +
#   coord_flip()
# 
# # grid.arrange(plot1, plot2, ncol=2)
# plt3 <- ggplotly(plt3)
```



```{r, warning=FALSE, message=FALSE, echo = FALSE}
# plt2 <- dat1 |>
#   filter(`Start Year` == 2018) |>
#   ggplot(aes(x = `Elementary Student Teacher Ratio`, y = `Grade 6 EQAO Reading Results`)) +
#   geom_point() +
#   geom_smooth(method=lm, se=FALSE, color = "blue") +
#   theme_minimal() +
#   labs(title = "Figure 6 - A scatterplot between elementary Student Teacher Ratio \nand grade 6 EQAO Reading Results for year 2018",
#        x = "Elementary Student Teacher Ratio",
#        y = "Grade 6 EQAO Reading Results")
# 
# plt2 <- ggplotly(plt2)

```



```{r, warning=FALSE, message=FALSE, echo = FALSE}

plt1 <- dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot(aes(x = `Suspension Rate`, y = `Grade 6 EQAO Reading Results`)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE, color = "blue") +
  theme_minimal() +
  labs(title = "Figure 7 - A scatterplot between suspension rate \nand grade 6 EQAO Reading Results for year 2018",
       x = "Suspension Rate",
       y = "Grade 6 EQAO Reading Results")

plt1 <- ggplotly(plt1)
  
```

```{r, include=FALSE, echo=FALSE}
temp1 <- dat1 |>
  filter(`Start Year` == 2018) |>
  select(c("Grade 6 EQAO Reading Results", "Elementary Student Teacher Ratio", "Suspension Rate")) |>
  rename(y = "Grade 6 EQAO Reading Results",
         x1 = "Elementary Student Teacher Ratio",
         x2 = "Suspension Rate")
m1 <- lm(y ~ x1 + x2, data = temp1)
summary(m1)
```

```{r, echo=FALSE, echo=FALSE}
c1 <- c("Interecpt", "Elementary Student Teacher Ratio", "Suspension Rate")
c2 <- c(0.779947, 0.006271, -2.101358)
c3 <- c(2e-16, 5.86e-12, 2e-16)

my_data <- data.frame(c1, c2, c3)
my_data <- my_data |>
  rename("Variable" = c1, "Estimated Beta" = c2, "p-value" = c3)

# datatable(
#   my_data, 
#   options = list(
#     scrollX = FALSE, 
#     scrollY = "300px",
#     paging = FALSE,
#     dom = 't'
#   ),
#   rownames = FALSE,
#   caption = "Table 3"
# ) %>%
# formatStyle(
#   columns = 1:3,
#   border = "1px solid black"
# )

```

## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
plt1
```

### Figure 2

```{r echo=FALSE}
plt2
```

### Figure 3
```{r echo=FALSE}
plt3
```


{-}