---
title: "JSC370 Final Project"
author: "Hongshuo Zhou"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

```{r load-data, echo=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

library(ggplot2)
library(leaflet)
library(readxl)
#install.packages("DT")
library(patchwork)
library(gridExtra)
library(stringr)
library(leaflet)

opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = FALSE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")

```


```{r, include=FALSE, echo=FALSE}
academic15 <- read_excel("academic15.xlsx")
academic15 <- academic15 |> 
  select(c("Board Number", "Board Name", "School Number", "School Name", "Street", "Latitude", "Longitude", 
           "Percentage of Grade 6 Students Achieving the Provincial Standard in Reading", "School Level",
           "Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))
academic15 <- academic15 |> 
  mutate('Start Year' = 2015)


### 16
academic16 <- read_excel("academic16.xlsx")
academic16 <- academic16 |> 
  select(c("Board Number", "Board Name", "School Number", "School Name", "Street", "Latitude", "Longitude", 
           "Percentage of Grade 6 Students Achieving the Provincial Standard in Reading", "School Level",
           "Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))
academic16 <- academic16 |> 
  mutate('Start Year' = 2016)

### 17
academic17 <- read_excel("academic17.xlsx")
academic17 <- academic17 |> 
  select(c("Board Number", "Board Name", "School Number", "School Name", "Street", "Latitude", "Longitude", 
           "Percentage of Grade 6 Students Achieving the Provincial Standard in Reading", "School Level",
           "Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))
academic17 <- academic17 |> 
  mutate('Start Year' = 2017)

### 18
academic18 <- read_excel("academic18.xlsx")
academic18 <- academic18 |> 
  select(c("Board Number", "Board Name", "School Number", "School Name", "Street", "Latitude", "Longitude", 
           "Percentage of Grade 6 Students Achieving the Provincial Standard in Reading", "School Level",
           "Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))
academic18 <- academic18 |> 
  mutate('Start Year' = 2018)

### 19
academic19 <- read_excel("academic19.xlsx")
academic19 <- academic19 |> 
  select(c("Board Number", "Board Name", "School Number", "School Name", "Street", "Latitude", "Longitude", 
           "Percentage of Grade 6 Students Achieving the Provincial Standard in Reading", "School Level",
           "Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))
academic19 <- academic19 |> 
  mutate('Start Year' = 2019)

academic <- rbind(academic15, academic16, academic17, academic18, academic19)

elementary <- academic |> filter(`School Level` == "Elementary")
secondary <- academic |> filter(`School Level` == "Secondary")

# clean_academic <- na.omit(academic)

## elementary
clean_elementary <- elementary |> filter(`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading` != "NA")
clean_elementary <- na.omit(clean_elementary)

clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading` <- str_sub(clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading`, end = -2) 

clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading` <- as.numeric(clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading`)
clean_elementary <- na.omit(clean_elementary)
clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading` <- clean_elementary$`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading` * 0.01 

clean_elementary <- clean_elementary |> select(-c("Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt"))


## secondary
clean_secondary <- secondary |> filter(`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt` != "NA")
clean_secondary <- na.omit(clean_secondary)

clean_secondary <- clean_secondary |> select(-c("Percentage of Grade 6 Students Achieving the Provincial Standard in Reading"))
clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt` <- str_sub(clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt`, end = -2)


clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt` <- as.numeric(clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt`)

clean_secondary <- na.omit(clean_secondary)
clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt` <- clean_secondary$`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt` * 0.01 

```

```{r, include=FALSE, echo=FALSE}
school_info <- read_excel("school_info.xlsx")
school_info <- school_info |>
  select("Region",
         "Board Number",
         "Board Name",
         "Board Language",
         "School Number",
         "School Name",
         "School Level",
         "School Language",
         "School Type",
         "City")
```

```{r, include=FALSE, echo=FALSE}

data8 <- read_excel("gender_2015.xlsx")
data8 <- data8 %>%
  mutate('Start Year' = 2015)

data9 <- read_excel("gender_2016.xlsx")
data9 <- data9 %>%
  mutate('Start Year' = 2016)

data10 <- read_excel("enrolment_by_gender_1718_en.xlsx")
data10 <- data10 %>%
  mutate('Start Year' = 2017)

data11 <- read_excel("enrolment_by_gender_1819_en.xlsx")
data11 <- data11 %>%
  mutate('Start Year' = 2018)

data12 <- read_excel("gender_1920_en.xlsx")
data12 <- data12 %>%
  mutate('Start Year' = 2019)

data11 <- data11 |>
  rename(
    `Elementary Male Enrolment` = `Elementary Male`,
    `Elementary Female Enrolment` = `Elementary Female`,
    `Secondary Male Enrolment` = `Secondary Male`,
    `Secondary Female Enrolment` = `Secondary Female`,
    `Total Male Enrolment` = `Total Male`,
    `Total Female Enrolment` = `Total Female`
  )

data12 <- data12 |>
  rename(
    `Elementary Male Enrolment` = `Elementary Male`,
    `Elementary Female Enrolment` = `Elementary Female`,
    `Secondary Male Enrolment` = `Secondary Male`,
    `Secondary Female Enrolment` = `Secondary Female`,
    `Total Male Enrolment` = `Total Male`,
    `Total Female Enrolment` = `Total Female`
  )

student <- rbind(data8, data9, data10, data11, data12)
```

```{r, include=FALSE, echo=FALSE}
data15 <- read_excel("edu_gender_1516_en.xlsx")
data15 <- data15 %>%
  mutate('Start Year' = 2015)

data16 <- read_excel("edu_gender_1617_en_0.xlsx")
data16 <- data16 %>%
  mutate('Start Year' = 2016)

data17 <- read_excel("edu_gender_1718.xlsx")
data17 <- data17 %>%
  mutate('Start Year' = 2017)

data18 <- read_excel("edu_gender_1819.xlsx")
data18 <- data18 %>%
  mutate('Start Year' = 2018)

data19 <- read_excel("edu_gender_1920.xlsx")
data19 <- data19 %>%
  mutate('Start Year' = 2019)

educator <- rbind(data15, data16, data17, data18, data19) |>
  select(-c("Academic Year"))


```

```{r, include=FALSE, echo=FALSE}
expulsion <- read_excel("expulsions_0708_2021.xlsx")
expulsion <- expulsion |>
  select("Board Number",
         "Board Name",
         "2007-2008 Expulsion Rate",
         "2008-2009 Expulsion Rate",
         "2009-2010 Expulsion Rate",
         "2010-2011 Expulsion Rate",
         "2011-2012 Expulsion Rate",
         "2012-2013 Expulsion Rate",
         "2013-2014 Expulsion Rate",
         "2014-2015 Expulsion Rate",
         "2015-2016 Expulsion Rate",
         "2016-2017 Expulsion Rate",
         "2017-2018 Expulsion Rate",
         "2018-2019 Expulsion Rate",
         "2019-2020 Expulsion Rate",
         "2020-2021 Expulsion Rate")

expulsion <- expulsion |>
  mutate("2007" = 2007,
         "2008" = 2008,
         "2009" = 2009,
         "2010" = 2010,
         "2011" = 2011,
         "2012" = 2012,
         "2013" = 2013,
         "2014" = 2014,
         "2015" = 2015,
         "2016" = 2016,
         "2017" = 2017,
         "2018" = 2018,
         "2019" = 2019,
         "2020" = 2020)

new_expulsion <- data.frame("Expulsion Rate" = c(
         expulsion$"2007-2008 Expulsion Rate",
         expulsion$"2008-2009 Expulsion Rate",
         expulsion$"2009-2010 Expulsion Rate",
         expulsion$"2010-2011 Expulsion Rate",
         expulsion$"2011-2012 Expulsion Rate",
         expulsion$"2012-2013 Expulsion Rate",
         expulsion$"2013-2014 Expulsion Rate",
         expulsion$"2014-2015 Expulsion Rate",
         expulsion$"2015-2016 Expulsion Rate",
         expulsion$"2016-2017 Expulsion Rate",
         expulsion$"2017-2018 Expulsion Rate",
         expulsion$"2018-2019 Expulsion Rate",
         expulsion$"2019-2020 Expulsion Rate",
         expulsion$"2020-2021 Expulsion Rate"),
         "Start Year" = c(
           expulsion$"2007",
         expulsion$"2008",
         expulsion$"2009",
         expulsion$"2010",
         expulsion$"2011",
         expulsion$"2012",
         expulsion$"2013",
         expulsion$"2014",
         expulsion$"2015",
         expulsion$"2016",
         expulsion$"2017",
         expulsion$"2018",
         expulsion$"2019",
         expulsion$"2020"
         ),
         "Board Name" = c(
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name",
           expulsion$"Board Name"
         ),
         "Board Number" = c(
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number",
           expulsion$"Board Number"
         ))
```

```{r, include=FALSE, echo=FALSE}
suspension <- read_excel("suspensions_0708-2021.xlsx")

suspension <- suspension |>
  select("Board Number",
         "Board Name",
         "2007-2008 Suspension Rate",
         "2008-2009 Suspension Rate",
         "2009-2010 Suspension Rate",
         "2010-2011 Suspension Rate",
         "2011-2012 Suspension Rate",
         "2012-2013 Suspension Rate",
         "2013-2014 Suspension Rate",
         "2014-2015 Suspension Rate",
         "2015-2016 Suspension Rate",
         "2016-2017 Suspension Rate",
         "2017-2018 Suspension Rate",
         "2018-2019 Suspension Rate",
         "2019-2020 Suspension Rate",
         "2020-2021 Suspension Rate")

suspension <- suspension |>
  mutate("2007" = 2007,
         "2008" = 2008,
         "2009" = 2009,
         "2010" = 2010,
         "2011" = 2011,
         "2012" = 2012,
         "2013" = 2013,
         "2014" = 2014,
         "2015" = 2015,
         "2016" = 2016,
         "2017" = 2017,
         "2018" = 2018,
         "2019" = 2019,
         "2020" = 2020)

new_suspension <- data.frame("Suspension Rate" = c(
         suspension$"2007-2008 Suspension Rate",
         suspension$"2008-2009 Suspension Rate",
         suspension$"2009-2010 Suspension Rate",
         suspension$"2010-2011 Suspension Rate",
         suspension$"2011-2012 Suspension Rate",
         suspension$"2012-2013 Suspension Rate",
         suspension$"2013-2014 Suspension Rate",
         suspension$"2014-2015 Suspension Rate",
         suspension$"2015-2016 Suspension Rate",
         suspension$"2016-2017 Suspension Rate",
         suspension$"2017-2018 Suspension Rate",
         suspension$"2018-2019 Suspension Rate",
         suspension$"2019-2020 Suspension Rate",
         suspension$"2020-2021 Suspension Rate"),
         "Start Year" = c(
           suspension$"2007",
         suspension$"2008",
         suspension$"2009",
         suspension$"2010",
         suspension$"2011",
         suspension$"2012",
         suspension$"2013",
         suspension$"2014",
         suspension$"2015",
         suspension$"2016",
         suspension$"2017",
         suspension$"2018",
         suspension$"2019",
         suspension$"2020"
         ),
         "Board Name" = c(
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name",
           suspension$"Board Name"
         ),
         "Board Number" = c(
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number",
           suspension$"Board Number"
         ))

# educator 
# student 
# academic c
# school_info c
# new expulsion c
# new suspension c

new_expulsion <- new_expulsion |> filter(2015 <= Start.Year) |> filter(Start.Year <= 2019)

new_suspension <- new_suspension |> filter(2015 <= Start.Year) |> filter(Start.Year <= 2019)

```


```{r, include = FALSE, echo=FALSE}

# merge for elementary
dat1 <- merge(
  # Data
  x = clean_elementary,
  y = educator,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Start Year.x` == `Start Year.y`) |>
  select(-c(`Board Name.y`, `Start Year.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Start Year" = `Start Year.x`)

dat1 <- dat1 |> select(-c("Secondary Male Educators", "Secondary Female Educators", "Total Male Educators", "Total Female Educators", "Total Educators"))
```

```{r, include = FALSE, echo=FALSE}
dat1 <- merge(
  # Data
  x = dat1,
  y = student,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Start Year.x` == `Start Year.y`) |>
  select(-c(`Board Name.y`, `Start Year.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Start Year" = `Start Year.x`)

dat1 <- dat1 |> select(-c("Secondary Male Enrolment", "Secondary Female Enrolment", "Total Male Enrolment", "Total Female Enrolment"))
```

```{r, include = FALSE, echo=FALSE}
school_info <- school_info |> rename("Geo-Region" = "Region")

dat1 <- merge(
  # Data
  x = dat1,
  y = school_info,
  # List of variables to match
  by.x = "School Number",
  by.y = "School Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Board Number.x` == `Board Number.y`,
         `School Name.x` == `School Name.y`,
         `School Level.x` == `School Level.y`,
         `Board Language.x` == `Board Language.y`) |>
  select(-c(`Board Name.y`, `Board Language.y`, `School Level.y`, `School Name.y`, `Board Number.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Board Number" = `Board Number.x`,
         "School Name" = `School Name.x`,
         "School Level" = `School Level.x`,
         "Board Language" = `Board Language.x`
         )

```

```{r, include = FALSE, echo=FALSE}
dat1 <- merge(
  # Data
  x = dat1,
  y = new_expulsion,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`))

```

```{r, include = FALSE, echo=FALSE}

dat1 <- merge(
  # Data
  x = dat1,
  y = new_suspension,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat1 <- dat1 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`)) |>
  rename("Expulsion Rate" = `Expulsion.Rate`,
         "Suspension Rate" = `Suspension.Rate`)

```

```{r}
## merge for secondary
dat2 <- merge(
  # Data
  x = clean_secondary,
  y = educator,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat2 <- dat2 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Start Year.x` == `Start Year.y`) |>
  select(-c(`Board Name.y`, `Start Year.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Start Year" = `Start Year.x`)

dat2 <- dat2 |> select(-c("Elementary Male Educators", "Elementary Female Educators", "Total Male Educators", "Total Female Educators", "Total Educators"))


dat2 <- merge(
  # Data
  x = dat2,
  y = student,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat2 <- dat2 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Start Year.x` == `Start Year.y`) |>
  select(-c(`Board Name.y`, `Start Year.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Start Year" = `Start Year.x`)

dat2 <- dat2 |> select(-c("Elementary Male Enrolment", "Elementary Female Enrolment", "Total Male Enrolment", "Total Female Enrolment"))


dat2 <- merge(
  # Data
  x = dat2,
  y = school_info,
  # List of variables to match
  by.x = "School Number",
  by.y = "School Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat2 <- dat2 |>
  filter(`Board Name.x` == `Board Name.y`,
         `Board Number.x` == `Board Number.y`,
         `School Name.x` == `School Name.y`,
         `School Level.x` == `School Level.y`,
         `Board Language.x` == `Board Language.y`) |>
  select(-c(`Board Name.y`, `Board Language.y`, `School Level.y`, `School Name.y`, `Board Number.y`)) |>
  rename("Board Name" = `Board Name.x`,
         "Board Number" = `Board Number.x`,
         "School Name" = `School Name.x`,
         "School Level" = `School Level.x`,
         "Board Language" = `Board Language.x`
         )

dat2 <- merge(
  # Data
  x = dat2,
  y = new_expulsion,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat2 <- dat2 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`))

dat2 <- merge(
  # Data
  x = dat2,
  y = new_suspension,
  # List of variables to match
  by.x = "Board Number",
  by.y = "Board.Number",
  # Which obs to keep?
  all.x = FALSE,
  all.y = FALSE
)

dat2 <- dat2 |>
  filter(`Start Year` == `Start.Year`) |>
  select(-c(`Start.Year`, `Board.Name`)) |>
  rename("Expulsion Rate" = `Expulsion.Rate`,
         "Suspension Rate" = `Suspension.Rate`)
```


```{r}
dat1$`Elementary Male Educators` <- as.numeric(dat1$`Elementary Male Educators`)
dat1$`Elementary Male Enrolment` <- as.numeric(dat1$`Elementary Male Enrolment`)
dat1$`Elementary Female Enrolment` <- as.numeric(dat1$`Elementary Female Enrolment`)
dat1 <- na.omit(dat1)

dat2$`Secondary Male Educators` <- as.numeric(dat2$`Secondary Male Educators`)
dat2$`Secondary Female Educators` <- as.numeric(dat2$`Secondary Female Educators`)
dat2$`Secondary Male Enrolment` <- as.numeric(dat2$`Secondary Male Enrolment`)
dat2$`Secondary Female Enrolment` <- as.numeric(dat2$`Secondary Female Enrolment`)
dat2 <- na.omit(dat2)
```



```{r, include=FALSE, echo=FALSE}
# create new variable student teacher ratio


dat1 <- dat1 |>
  mutate("Elementary Student Teacher Ratio" = (`Elementary Male Enrolment` + `Elementary Female Enrolment`) /
           (`Elementary Male Educators` + `Elementary Female Educators`))

dat2 <- dat2 |> 
  mutate("Secondary Student Teacher Ratio" = (`Secondary Male Enrolment` + `Secondary Female Enrolment`) / 
           (`Secondary Male Educators` + `Secondary Female Educators`))
```



```{r, echo=FALSE}
datatable(
  head(dat1, 5),
  options = list(
    scrollX = TRUE,
    scrollY = FALSE,
    paging = FALSE,
    dom = 't'
  ),
  rownames = FALSE,
  caption = "Table 1 - First 5 rows of the final merged dataset"
) |>
formatStyle(
  columns = 1:34,
  border = "0.5px solid black"
)

```



```{r, echo=FALSE, echo=FALSE}
# data <- read.csv("document.csv")
# 
# data <- data |>
#   select(-("ID")) |>
#   rename("Variable Name" = Variable.Name,
#          "Variable Description" = Occupational.title)

# datatable(
#   data, 
#   options = list(
#     scrollX = FALSE, 
#     scrollY = "300px",
#     paging = FALSE,
#     dom = 't'
#   ),
#   rownames = FALSE,
#   caption = "Table 2"
# ) %>%
# formatStyle(
#   columns = 1:2,
#   border = "1px solid black"
# )
```



```{r, echo = FALSE, echo=FALSE}
dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_bar(aes(x = `Geo-Region`, fill = `Geo-Region`)) +
  labs(title = "Figure 1 - A barplot of the number of schools in each region",
       y = "Count",
       x = "School Region") +
  coord_flip() +
  theme_bw()

# plt3 <- ggplotly(plt3)
```


```{r, echo = FALSE, warning=FALSE, echo=FALSE}
dat1$`Start Year` <- as.factor(dat1$`Start Year`)

dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_histogram(aes(x = `Elementary Student Teacher Ratio`), fill = "orange", color = "black", bins=30) +
  labs(title = "Figure 2 - A histogram of the Secondary Student-Teacher Ratio",
       y = "Count",
       x = "Secondary Student Teacher Ratio") +
  theme_bw()
```

```{r, echo=FALSE, warning=FALSE, echo=FALSE}
dat1 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_histogram(aes(x = `Elementary Student Teacher Ratio`), fill = "orange", color = "black", bins=30) +
  labs(title = "Figure 3 - A histogram of the Elementary Student-Teacher Ratio",
       y = "Count",
       x = "Elementary Student Teacher Ratio") +
  theme_bw()

dat2 |>
  filter(`Start Year` == 2018) |>
  ggplot() +
  geom_histogram(aes(x = `Secondary Student Teacher Ratio`), fill = "orange", color = "black", bins=30) +
  labs(title = "Figure 3 - A histogram of the Elementary Student-Teacher Ratio",
       y = "Count",
       x = "Elementary Student Teacher Ratio") +
  theme_bw()

# grid.arrange(plot1, plot2, ncol=1)
# plt2 <- ggplotly(plt2)
```


```{r, echo=FALSE}

# dat1$`Grade 10 OSSLT Results` <- as.numeric(dat1$`Grade 10 OSSLT Results`)

dat1 |>
  ggplot() +
  geom_boxplot(aes(x = `Percentage of Grade 6 Students Achieving the Provincial Standard in Reading`, fill=`Geo-Region`), color = "black") +
  labs(title = "Figure 4 - A boxplot for \nthe Grade 10 OSSLT Results",
       x = "Grade 10 OSSLT Results") +
  scale_fill_brewer(palette = "Paired") +
  theme_bw() +
  coord_flip()

dat2 |>
  ggplot() +
  geom_boxplot(aes(x = `Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt`, fill=`Geo-Region`), color = "black") +
  labs(title = "Figure 4 - A boxplot for \nthe Grade 10 OSSLT Results",
       x = "Grade 10 OSSLT Results") +
  scale_fill_brewer(palette = "Paired") +
  theme_bw() +
  coord_flip()

# plt3 <- dat1 |>
#   ggplot() +
#   geom_boxplot(aes(x = `Grade 6 EQAO Reading Results`), fill="gray", color = "black") +
#   labs(title = "Figure 5 - A boxplot for \nGrade 6 EQAO Reading Results",
#        x = "Grade 6 EQAO Reading Results") +
#   scale_fill_brewer(palette = "Paired") +
#   theme_bw() +
#   coord_flip()
# 
# # grid.arrange(plot1, plot2, ncol=2)
# plt3 <- ggplotly(plt3)

dat1 |> 
  ggplot() +
  geom_point(aes(x=`Start Year`, y = `Percentage of Grade 6 Students Achieving the Provincial Standard in Reading`, fill = `Geo-Region`))

dat1 |> group_by(`Geo-Region`, `Start Year`) |> summarize(mean = mean(`Percentage of Grade 6 Students Achieving the Provincial Standard in Reading`)) |> ggplot() + geom_point(aes(x=`Start Year`, y=mean, color = `Geo-Region`)) + geom_line(aes(x=`Start Year`, y = `mean`, color = `Geo-Region`, group = `Geo-Region`)) + theme_bw()

dat2 |> group_by(`Geo-Region`, `Start Year`) |> summarize(mean = mean(`Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt`)) |> ggplot() + geom_point(aes(x=`Start Year`, y=mean, color = `Geo-Region`)) + geom_line(aes(x=`Start Year`, y = `mean`, color = `Geo-Region`, group = `Geo-Region`)) + theme_bw()
```



```{r, warning=FALSE, message=FALSE, echo = FALSE}
# plt2 <- dat1 |>
#   filter(`Start Year` == 2018) |>
#   ggplot(aes(x = `Elementary Student Teacher Ratio`, y = `Grade 6 EQAO Reading Results`)) +
#   geom_point() +
#   geom_smooth(method=lm, se=FALSE, color = "blue") +
#   theme_minimal() +
#   labs(title = "Figure 6 - A scatterplot between elementary Student Teacher Ratio \nand grade 6 EQAO Reading Results for year 2018",
#        x = "Elementary Student Teacher Ratio",
#        y = "Grade 6 EQAO Reading Results")
# 
# plt2 <- ggplotly(plt2)

```



```{r, warning=FALSE, message=FALSE, echo = FALSE}

# plt1 <- dat1 |>
#   filter(`Start Year` == 2018) |>
#   ggplot(aes(x = `Suspension Rate`, y = `Grade 6 EQAO Reading Results`)) +
#   geom_point() +
#   geom_smooth(method=lm, se=FALSE, color = "blue") +
#   theme_minimal() +
#   labs(title = "Figure 7 - A scatterplot between suspension rate \nand grade 6 EQAO Reading Results for year 2018",
#        x = "Suspension Rate",
#        y = "Grade 6 EQAO Reading Results")
# 
# plt1 <- ggplotly(plt1)
  
```

```{r, include=FALSE, echo=FALSE}
# temp1 <- dat1 |>
#   filter(`Start Year` == 2018) |>
#   select(c("Grade 6 EQAO Reading Results", "Elementary Student Teacher Ratio", "Suspension Rate")) |>
#   rename(y = "Grade 6 EQAO Reading Results",
#          x1 = "Elementary Student Teacher Ratio",
#          x2 = "Suspension Rate")
# m1 <- lm(y ~ x1 + x2, data = temp1)
# summary(m1)
```

```{r, echo=FALSE, echo=FALSE}
# c1 <- c("Interecpt", "Elementary Student Teacher Ratio", "Suspension Rate")
# c2 <- c(0.779947, 0.006271, -2.101358)
# c3 <- c(2e-16, 5.86e-12, 2e-16)
# 
# my_data <- data.frame(c1, c2, c3)
# my_data <- my_data |>
#   rename("Variable" = c1, "Estimated Beta" = c2, "p-value" = c3)

# datatable(
#   my_data, 
#   options = list(
#     scrollX = FALSE, 
#     scrollY = "300px",
#     paging = FALSE,
#     dom = 't'
#   ),
#   rownames = FALSE,
#   caption = "Table 3"
# ) %>%
# formatStyle(
#   columns = 1:3,
#   border = "1px solid black"
# )

```

```{r}
# stations_map <- leaflet() |>
#   addProviderTiles("CartoDB.Positron") |>
#   addCircles(
#     data = dat1,
#     lat = ~Latitude, lng = ~Longitude, popup = "Geospatial mid",
#     opacity = 1, fillOpacity = 1, radius = 20, color = "darkgreen")
#   # ) |>
#   # addLegend(
#   #   colors = c("darkgreen", "purple"),
#   #   labels = c("Geospatially middle stations", "Climate representative stations")
#   # )
# 
# # mapview::mapshot(stations_map, file = "mapview.png")
# stations_map
```



## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
# plt1
```

### Figure 2

```{r echo=FALSE}
# plt2
```

### Figure 3
```{r echo=FALSE}
# plt3
```

{-}